### ISSUE TITLE
@sayakpaul UBUNTU Environment issue

### ISSUE THREAD

**Issue by sree3333** [huggingface/instruction-tuned-sd#20]
@sayakpaul How could your finetuning code run with 6GB graphic card on windows but not 12GB and 16GB cards on ubuntu?
I suspect there might be some issue with your code, please throughly check your code once.

_Originally posted by @sree3333 in https://github.com/huggingface/instruction-tuned-sd/issues/19#issuecomment-1947955570_

**Comment by sayakpaul** [comment]
It's not on my priority. It runs as expected on the provided settings in the README. Plus I just tested it on two 4090s and it still works. 

<img width="1511" alt="Screenshot 2024-02-16 at 2 33 38 PM" src="https://github.com/huggingface/instruction-tuned-sd/assets/22957388/752ed295-b85f-4e97-948b-93d48e966a51">

Command used:

```bash
CUDA_VISIBLE_DEVICES=0 accelerate launch --mixed_precision="fp16" finetune_instruct_pix2pix.py \
  --pretrained_model_name_or_path="timbrooks/instruct-pix2pix" \
  --dataset_name="instruction-tuning-sd/cartoonization" \
  --use_ema \
  --enable_xformers_memory_efficient_attention \
  --resolution=256 --random_flip \
  --train_batch_size=2 --gradient_accumulation_steps=4 --gradient_checkpointing \
  --max_train_steps=15000 \
  --checkpointing_steps=5000 --checkpoints_total_limit=1 \
  --learning_rate=5e-05 --lr_warmup_steps=0 \
  --mixed_precision=fp16 \
  --val_image_url="https://hf.co/datasets/diffusers/diffusers-images-docs/resolve/main/mountain.png" \
  --validation_prompt="Generate a cartoonized version of the natural image" \
  --seed=42 \
  --output_dir="cartoonization-finetuned"
```

It's not possible for me to check on every GPU card. So, I won't be able to further get back on this, I am afraid. So, I advise you to thoroughly check the installation, setup, command, dataset, etc. More so, because I have now already confirmed and shown it works.

**Comment by sree3333** [comment]
I have tried using the same command but still getting cuda out of memory error

**Comment by sree3333** [comment]
@sayakpaul I am talking more about the environmnent than about the GPU. Your code is not running in ubuntu ENV. Please try to understand the problem statement and resolve the issue rather than closing the issue before any resolution.

**Comment by sayakpaul** [comment]
It's working perfectly fine in my Ubuntu environment. So, I don't see anything actionable on my end.
